Basic analysis
hochschule-darmstadt/MetaAutoML pull request #91
Opened 2022-06-02 10:35 UTC by rnbndr

Basic analysis of the dataset containing information about:
- number of rows and columns
- missing values per column
- rows with a lot of missing values
- outlier detection

2022-06-02 13:21 UTC, bican-guel commented
Sorry for the possible millions of messages for my reviews and comments. I was having issues with Github.

2022-06-02 16:45 UTC, jnnks requested changes
You are passing around and returning the jsonfile quite a lot.
I think you should change your functions to only take the dataset as an input and then return any output as a separate value. Then the analysis dictionary can be built together in the startAnalysis function:
```python
 jsonfile["basic analysis"] = {
  "outlier": __detect_outliers(dataset),
  ...
}
```
That way we can use the functions in the module without having to construct a result dictionary and still get meaningful results. It also reduces the amount of hardcoded string keys.
____
**Optional**
Think about the names you give your keys and variables. They should be short, but unique and descriptive.
Without reading the right side of an assignment what is the difference between `column` and `current_column` in line 108+? What about `current_column` in line 126? :D

Please remove the spaces in dictionary keys. Treat them just like variable names.
You will not remember whether the key is `rows with many missing values` or `rows with missing values` and neither will someone else :) use something like `high_na_rows`

____

The logic seems good to me. I'm sure some statements can be shorter like line 79+, but that's not important as long as it works and can be understood.
I'm happy so far, if you add the comments and restructure the methods

2022-06-02 16:45 UTC, jnnks commented on controller/managers/DataSetAnalysisManager.py
> +            IQR = Q3 - Q1
Why not name IQR `interquartile_range`? :D

2022-06-02 19:45 UTC, jnnks commented on controller/managers/DataSetAnalysisManager.py
> +            jsonfile["basic analysis"]["missing values in columns"][index] = value
Can be shorter:
```python
# map all columns with the number of missing values
na_counts = dict(dataset.isna().sum().items())
```

2022-06-05 18:50 UTC, bican-guel commented
@jnnks 
Just a friendly reminder.
All your requests have been fulfilled.

As its your initial review please approve for the merge.^^

2022-06-05 19:16 UTC, jnnks commented
@rnbndr could you fix the methods return types?
I assume the last two methods `__detect_duplicate_columns` and `__detect_duplicate_rows` are a work in progress?
They do not seem to make a change. Could you take them out of this PR in this case? We should not merge WIP code.

2022-06-06 08:49 UTC, jnnks approved these changes

2022-06-06 08:52 UTC, merged

2022-06-06 08:53 UTC, jnnks commented
squashed and merged
I'll leave the branch so you can continue working on it :)